//
// Created by ningsheng on 2020/10/25.
//

#ifndef LINUX_SYSTEM_LEARN_STANDARD_IO_LEARN_H
#define LINUX_SYSTEM_LEARN_STANDARD_IO_LEARN_H
int printf_learn();
#endif //LINUX_SYSTEM_LEARN_STANDARD_IO_LEARN_H
